### PR TITLE
Removed async dependency

### PR DESCRIPTION
**Pull request by maxx-t**
This pull request is an aggregate of several merged modifications:
- Running all tests in one call: 
  - Tests are now chained and runs from a single entrypoint (see [branch here](https://github.com/maxx-t/ledger-node-js-api/tree/tests))
- Added timeout option on ledger-comm-u2f (see branch [here](https://github.com/maxx-t/ledger-node-js-api/tree/timeout) or commit [here](https://github.com/maxx-t/ledger-node-js-api/commit/9fcb3188a23925f09b11900271797b6bc28ca442))
- Using browserify's standalone option to export ledger api (see branch [here](https://github.com/maxx-t/ledger-node-js-api/tree/improve-broserify) or commit [here](https://github.com/maxx-t/ledger-node-js-api/commit/a6da6a6b3e35b69ffae7878f2fe15fe2a80b3794))
- Polyfilled eachSeries function & removed the "async" module dependency from ledger-btc (see [here](https://github.com/maxx-t/ledger-node-js-api/commit/c3ebcc79b6977a8116b150df393bf4ed293817e1))

Those modifications aimed to make the API lighter, especially for the browserified version; without the async dependency the browserified api went from 357KB to 181KB (11k lines to 6k)

### CODE REVIEW

**Comment by antony** [comment]
This is a great PR. Any reason that it has been ignored?

**Comment by btchip** [comment]
Lack of time to review it mostly. Will try my best, no ETA

**Comment by antony** [comment]
np @btchip I understand your pain! I am thinking of a PR for removing Q but I didn't want to spend time on it if nobody was reviewing.

Will open a PR asap :)

**Comment by maxx-t** [comment]
@antony I already have something ready were Q was removed too, I'm just waiting for this one to be accepted first.

**Comment by btchip** [comment]
ok, I'll do my best to review in the coming days - since I also need to touch it now to add Segwit support

**Comment by btchip** [comment]
done, ready for the next one :)

**Comment by maxx-t** [comment]
Nice :) issue #9 is no longer relevant now. I'm preparing a PR to remove "q", and will propose it as soon as I can put my hands on a Leger device to test it ;)

**Comment by antony** [comment]
@maxx-t I have a Ledger here and waiting - if there is something I can do, please let me know,

**Comment by maxx-t** [comment]
@antony done on PR #18  :)

**Pull request merged**
